#pragma once

#ifndef VLC_RX_HALF_BIT_US
#define VLC_RX_HALF_BIT_US 40U
#endif

#ifndef VLC_RX_SAMPLES_PER_HALF
#define VLC_RX_SAMPLES_PER_HALF 8U
#endif

#ifndef VLC_RX_SAMPLES_PER_BIT
#define VLC_RX_SAMPLES_PER_BIT (VLC_RX_SAMPLES_PER_HALF * 2U)
#endif

#ifndef VLC_RX_SAMPLE_RATE_HZ
#define VLC_RX_SAMPLE_RATE_HZ \
  ((1000000UL * VLC_RX_SAMPLES_PER_HALF) / VLC_RX_HALF_BIT_US)
#endif

#ifndef VLC_RX_SERIAL_BAUD
#define VLC_RX_SERIAL_BAUD 115200U
#endif

#ifndef VLC_RX_MAX_PAYLOAD_LEN
#define VLC_RX_MAX_PAYLOAD_LEN 255U
#endif

#ifndef VLC_RX_PREAMBLE_MIN_EDGES
#define VLC_RX_PREAMBLE_MIN_EDGES 12U
#endif
